name: "Security Analysis"
description: "Run security analysis tools"

inputs:
    tool:
        description: "Security tool to run (brakeman)"
        required: true

runs:
    using: "composite"
    steps:
        - name: Update dependencies
          shell: bash
          run: |
              bundle update
              bun update

                - name: Run Brakeman
          if: inputs.tool == 'brakeman'
          shell: bash
                      run: bundle exec brakeman -A --except WeakHash --quiet --no-summary --no-pager
