name: "Security Analysis"
description: "Run security analysis tools"

inputs:
    tool:
        description: "Security tool to run (brakeman, bundle-audit, npm-audit)"
        required: true

runs:
    using: "composite"
    steps:
        - name: Update dependencies
          shell: bash
          run: |
              bundle update
              bun update

        - name: Run Brakeman
          if: inputs.tool == 'brakeman'
          shell: bash
          run: bundle exec brakeman --quiet --no-summary --no-pager

        - name: Run bundle-audit
          if: inputs.tool == 'bundle-audit'
          shell: bash
          run: bundle exec bundle-audit check --update

        - name: Run npm audit (production only)
          if: inputs.tool == 'npm-audit'
          shell: bash
          run: |
              # Backup existing package-lock.json if it exists
              if [ -f package-lock.json ]; then cp package-lock.json package-lock.json.backup; fi
              npm i --package-lock-only --omit=dev --omit=optional --omit=peer --legacy-peer-deps --force
              npm audit --audit-level=moderate
              # Restore original package-lock.json if backup exists, otherwise remove generated one
              if [ -f package-lock.json.backup ]; then mv package-lock.json.backup package-lock.json; else rm -f package-lock.json; fi
