# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `foundation_emails` gem.
# Please instead update this file by running `bin/tapioca gem foundation_emails`.


# source://foundation_emails//lib/foundation_emails/version.rb#1
module FoundationEmails; end

# source://foundation_emails//lib/foundation_emails/engine.rb#4
class FoundationEmails::Engine < ::Rails::Engine; end

# source://foundation_emails//lib/foundation_emails/version.rb#2
FoundationEmails::VERSION = T.let(T.unsafe(nil), String)
