# typed: strict

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `kaminari-i18n` gem.
# Please instead update this file by running `bin/tapioca gem kaminari-i18n`.


# source://kaminari-i18n//lib/kaminari-i18n/version.rb#1
module KaminariI18n; end

# source://kaminari-i18n//lib/kaminari-i18n/engine.rb#4
class KaminariI18n::Engine < ::Rails::Engine; end

# source://kaminari-i18n//lib/kaminari-i18n/version.rb#2
KaminariI18n::VERSION = T.let(T.unsafe(nil), String)
