# typed: strict

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `kramdown-math-katex` gem.
# Please instead update this file by running `bin/tapioca gem kramdown-math-katex`.


# THIS IS AN EMPTY RBI FILE.
# see https://github.com/Shopify/tapioca#manually-requiring-parts-of-a-gem
