# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `passenger` gem.
# Please instead update this file by running `bin/tapioca gem passenger`.


# source://passenger//src/ruby_supportlib/phusion_passenger.rb#26
module PhusionPassenger
  class << self
    # source://passenger//src/ruby_supportlib/phusion_passenger.rb#198
    def apache2_module_path; end

    # source://passenger//src/ruby_supportlib/phusion_passenger.rb#198
    def bin_dir; end

    # Other resource locations ######
    #
    # source://passenger//src/ruby_supportlib/phusion_passenger.rb#221
    def binaries_sites; end

    # source://passenger//src/ruby_supportlib/phusion_passenger.rb#198
    def build_system_dir; end

    # source://passenger//src/ruby_supportlib/phusion_passenger.rb#254
    def call_event(name, *args); end

    # @return [Boolean]
    #
    # source://passenger//src/ruby_supportlib/phusion_passenger.rb#152
    def custom_packaged?; end

    # source://passenger//src/ruby_supportlib/phusion_passenger.rb#198
    def doc_dir; end

    # source://passenger//src/ruby_supportlib/phusion_passenger.rb#198
    def download_cache_dir; end

    # source://passenger//src/ruby_supportlib/phusion_passenger.rb#204
    def find_support_binary(name); end

    # source://passenger//src/ruby_supportlib/phusion_passenger.rb#317
    def get_bool_option(filename, options, key); end

    # source://passenger//src/ruby_supportlib/phusion_passenger.rb#306
    def get_option(filename, options, key, required = T.unsafe(nil)); end

    # source://passenger//src/ruby_supportlib/phusion_passenger.rb#198
    def helper_scripts_dir; end

    # The HOME environment variable is often unreliable, because for
    # example `sudo` preserves it. That's why we don't respect it by
    # default.
    #
    # source://passenger//src/ruby_supportlib/phusion_passenger.rb#325
    def home_dir(respect_home_env = T.unsafe(nil)); end

    # source://passenger//src/ruby_supportlib/phusion_passenger.rb#198
    def include_dir; end

    # source://passenger//src/ruby_supportlib/phusion_passenger.rb#262
    def infer_install_spec; end

    # The installation specification string, as passed to #locate_directories.
    #
    # source://passenger//src/ruby_supportlib/phusion_passenger.rb#185
    def install_spec; end

    # Whether the current Phusion Passenger installation is installed
    # from a release package, e.g. an official gem or official tarball.
    # Returns false if e.g. the gem was built by the user, or if this
    # install is from a git repository.
    #
    # @return [Boolean]
    #
    # source://passenger//src/ruby_supportlib/phusion_passenger.rb#180
    def installed_from_release_package?; end

    # source://passenger//src/ruby_supportlib/phusion_passenger.rb#198
    def lib_dir; end

    # Follows the logic of src/cxx_supportlib/ResourceLocator.h, so don't forget to modify that too.
    #
    # source://passenger//src/ruby_supportlib/phusion_passenger.rb#102
    def locate_directories(install_spec = T.unsafe(nil)); end

    # source://passenger//src/ruby_supportlib/phusion_passenger.rb#198
    def nginx_module_source_dir; end

    # source://passenger//src/ruby_supportlib/phusion_passenger.rb#198
    def node_libdir; end

    # Forward define public_api.rb methods for code that tries to hook
    # Passenger events before an app is spawned (such as mongoid)
    #
    # source://passenger//src/ruby_supportlib/phusion_passenger.rb#248
    def on_event(name, &block); end

    # Returns whether this Phusion Passenger installation is in the 'originally packaged'
    # configuration (as opposed to the 'custom packaged' configuration.
    #
    # @return [Boolean]
    #
    # source://passenger//src/ruby_supportlib/phusion_passenger.rb#148
    def originally_packaged?; end

    # If Phusion Passenger is custom packaged, returns which packaging
    # method was used. Can be 'deb', 'rpm', 'homebrew', 'test'
    # or 'unknown'.
    #
    # source://passenger//src/ruby_supportlib/phusion_passenger.rb#159
    def packaging_method; end

    # source://passenger//src/ruby_supportlib/phusion_passenger.rb#163
    def packaging_method_description; end

    # source://passenger//src/ruby_supportlib/phusion_passenger.rb#287
    def parse_ini_file(filename); end

    # Instead of calling `require 'phusion_passenger/foo'`, you should call
    # `PhusionPassenger.require_passenger_lib 'foo'`. This is because when Phusion
    # Passenger is natively packaged, it may still be run with arbitrary Ruby
    # interpreters. Adding ruby_libdir to $LOAD_PATH is then dangerous because ruby_libdir
    # may be the distribution's Ruby's vendor_ruby directory, which may be incompatible
    # with the active Ruby interpreter. This method looks up the exact filename directly.
    #
    # Using this method also has two more advantages:
    #
    #  1. It is immune to Bundler's load path mangling code.
    #  2. It is faster than plain require() because it doesn't need to
    #     scan the entire load path.
    #
    # source://passenger//src/ruby_supportlib/phusion_passenger.rb#242
    def require_passenger_lib(name); end

    # source://passenger//src/ruby_supportlib/phusion_passenger.rb#198
    def resources_dir; end

    # source://passenger//src/ruby_supportlib/phusion_passenger.rb#198
    def ruby_extension_source_dir; end

    # source://passenger//src/ruby_supportlib/phusion_passenger.rb#198
    def ruby_libdir; end

    # source://passenger//src/ruby_supportlib/phusion_passenger.rb#198
    def support_binaries_dir; end

    # source://passenger//src/ruby_supportlib/phusion_passenger.rb#200
    def user_support_binaries_dir; end
  end
end

# The name for the /etc/apache2/mods-available/*.{load,conf} file.
#
# source://passenger//src/ruby_supportlib/phusion_passenger.rb#58
PhusionPassenger::APACHE2_MODULE_CONF_NAME = T.let(T.unsafe(nil), String)

# source://passenger//src/ruby_supportlib/phusion_passenger.rb#27
PhusionPassenger::FILE_LOCATION = T.let(T.unsafe(nil), String)

# Directories ######
#
# source://passenger//src/ruby_supportlib/phusion_passenger.rb#54
PhusionPassenger::GLOBAL_NAMESPACE_DIRNAME_ = T.let(T.unsafe(nil), String)

# source://passenger//src/ruby_supportlib/phusion_passenger.rb#38
PhusionPassenger::NGINX_SHA256_CHECKSUM = T.let(T.unsafe(nil), String)

# source://passenger//src/ruby_supportlib/phusion_passenger.rb#93
PhusionPassenger::OPTIONAL_LOCATIONS_INI_FIELDS = T.let(T.unsafe(nil), Array)

# Names and version numbers ######
#
# source://passenger//src/ruby_supportlib/phusion_passenger.rb#32
PhusionPassenger::PACKAGE_NAME = T.let(T.unsafe(nil), String)

# source://passenger//src/ruby_supportlib/phusion_passenger.rb#43
PhusionPassenger::PACKAGING_NGINX_SHA256_CHECKSUM = T.let(T.unsafe(nil), String)

# Packaging may be locked to an older version due to the specific module configuration being
# incompatible with the version we prefer (latest stable).
#
# source://passenger//src/ruby_supportlib/phusion_passenger.rb#42
PhusionPassenger::PACKAGING_PREFERRED_NGINX_VERSION = T.let(T.unsafe(nil), String)

# source://passenger//src/ruby_supportlib/phusion_passenger.rb#47
PhusionPassenger::PCRE_SHA256_CHECKSUM = T.let(T.unsafe(nil), String)

# Directories in which to look for plugins.
#
# source://passenger//src/ruby_supportlib/phusion_passenger.rb#61
PhusionPassenger::PLUGIN_DIRS = T.let(T.unsafe(nil), Array)

# Tip: find the SHA-256 with ./dev/nginx_version_sha256 <VERSION>
#
# source://passenger//src/ruby_supportlib/phusion_passenger.rb#37
PhusionPassenger::PREFERRED_NGINX_VERSION = T.let(T.unsafe(nil), String)

# sha256sum of the .tar.gz
#
# source://passenger//src/ruby_supportlib/phusion_passenger.rb#46
PhusionPassenger::PREFERRED_PCRE_VERSION = T.let(T.unsafe(nil), String)

# source://passenger//src/ruby_supportlib/phusion_passenger.rb#67
PhusionPassenger::REQUIRED_LOCATIONS_INI_FIELDS = T.let(T.unsafe(nil), Array)

# source://passenger//src/ruby_supportlib/phusion_passenger/rack/handler.rb#28
module PhusionPassenger::Rack; end

# source://passenger//src/ruby_supportlib/phusion_passenger/rack/handler.rb#29
module PhusionPassenger::Rack::Handler
  # source://passenger//src/ruby_supportlib/phusion_passenger/rack/handler.rb#38
  def environment; end

  # source://passenger//src/ruby_supportlib/phusion_passenger/rack/handler.rb#30
  def run(app, options = T.unsafe(nil)); end

  # source://passenger//src/ruby_supportlib/phusion_passenger/rack/handler.rb#42
  def to_s; end

  private

  # source://passenger//src/ruby_supportlib/phusion_passenger/rack/handler.rb#47
  def build_args(options); end

  # source://passenger//src/ruby_supportlib/phusion_passenger/rack/handler.rb#68
  def find_passenger_standalone; end

  # source://passenger//src/ruby_supportlib/phusion_passenger/rack/handler.rb#55
  def rb_config; end

  # source://passenger//src/ruby_supportlib/phusion_passenger/rack/handler.rb#63
  def ruby_executable; end
end

# source://passenger//src/ruby_supportlib/phusion_passenger.rb#49
PhusionPassenger::STANDALONE_INTERFACE_VERSION = T.let(T.unsafe(nil), Integer)

# Subdirectory under $HOME to use for storing stuff.
#
# source://passenger//src/ruby_supportlib/phusion_passenger.rb#56
PhusionPassenger::USER_NAMESPACE_DIRNAME_ = T.let(T.unsafe(nil), String)

# Run 'rake src/cxx_supportlib/Constants.h configkit_schemas_inline_comments' after changing this number.
#
# source://passenger//src/ruby_supportlib/phusion_passenger.rb#34
PhusionPassenger::VERSION_STRING = T.let(T.unsafe(nil), String)

# source://passenger//src/ruby_supportlib/phusion_passenger/rack_handler.rb#45
module Rackup; end

# source://passenger//src/ruby_supportlib/phusion_passenger/rack_handler.rb#46
module Rackup::Handler
  class << self
    # source://passenger//src/ruby_supportlib/phusion_passenger/rack_handler.rb#53
    def default(options = T.unsafe(nil)); end
  end
end

# source://passenger//src/ruby_supportlib/phusion_passenger/rack_handler.rb#47
module Rackup::Handler::PhusionPassenger
  extend ::PhusionPassenger::Rack::Handler
end
