# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rails_gravatar` gem.
# Please instead update this file by running `bin/tapioca gem rails_gravatar`.


# source://rails_gravatar//lib/rails_gravatar.rb#6
class RailsGravatar
  include ::ActionView::Helpers::CaptureHelper
  include ::ActionView::Helpers::OutputSafetyHelper
  include ::ActionView::Helpers::TagHelper

  # @return [RailsGravatar] a new instance of RailsGravatar
  #
  # source://rails_gravatar//lib/rails_gravatar.rb#25
  def initialize(email_address = T.unsafe(nil), size = T.unsafe(nil), fallback_image_url = T.unsafe(nil), alt_text = T.unsafe(nil)); end

  # source://rails_gravatar//lib/rails_gravatar.rb#46
  def email_address; end

  # source://rails_gravatar//lib/rails_gravatar.rb#42
  def email_address_digest; end

  # source://rails_gravatar//lib/rails_gravatar.rb#64
  def fallback_image_url_param; end

  # source://rails_gravatar//lib/rails_gravatar.rb#72
  def prefetch_dns_tag; end

  # source://rails_gravatar//lib/rails_gravatar.rb#54
  def size; end

  # source://rails_gravatar//lib/rails_gravatar.rb#50
  def size_param; end

  # source://rails_gravatar//lib/rails_gravatar.rb#32
  def src; end

  # source://rails_gravatar//lib/rails_gravatar.rb#68
  def tag; end

  class << self
    # source://rails_gravatar//lib/rails_gravatar.rb#12
    def prefetch_dns_tag; end

    # source://rails_gravatar//lib/rails_gravatar.rb#16
    def src(email_address, size = T.unsafe(nil), fallback_image_url = T.unsafe(nil)); end

    # source://rails_gravatar//lib/rails_gravatar.rb#20
    def tag(email_address, size = T.unsafe(nil), fallback_image_url = T.unsafe(nil), alt_text = T.unsafe(nil)); end
  end
end

# source://rails_gravatar//lib/rails_gravatar.rb#9
RailsGravatar::DEFAULT_SIZE = T.let(T.unsafe(nil), Integer)
