# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rodauth-oauth` gem.
# Please instead update this file by running `bin/tapioca gem rodauth-oauth`.


# :nocov:
#
# source://rodauth-oauth//lib/rodauth/oauth/version.rb#3
module Rodauth; end

module Rodauth::Base; end
module Rodauth::EmailBase; end

class Rodauth::Feature < ::Module
  include ::Rodauth::OAuth::FeatureExtensions
end

# source://rodauth-oauth//lib/rodauth/oauth/version.rb#4
module Rodauth::OAuth; end

# source://rodauth-oauth//lib/rodauth/oauth/railtie.rb#5
module Rodauth::OAuth::ControllerMethods
  # source://rodauth-oauth//lib/rodauth/oauth/railtie.rb#11
  def current_oauth_account(name = T.unsafe(nil)); end

  # source://rodauth-oauth//lib/rodauth/oauth/railtie.rb#15
  def current_oauth_application(name = T.unsafe(nil)); end

  class << self
    # @private
    #
    # source://rodauth-oauth//lib/rodauth/oauth/railtie.rb#6
    def included(controller); end
  end
end

# source://rodauth-oauth//lib/rodauth/oauth.rb#8
module Rodauth::OAuth::FeatureExtensions
  # source://rodauth-oauth//lib/rodauth/oauth.rb#9
  def auth_server_route(name, *args, &blk); end

  # override
  #
  # source://rodauth-oauth//lib/rodauth/oauth.rb#28
  def translatable_method(meth, value); end
end

# source://rodauth-oauth//lib/rodauth/oauth/railtie.rb#20
class Rodauth::OAuth::Railtie < ::Rails::Railtie; end

# source://rodauth-oauth//lib/rodauth/oauth/version.rb#5
Rodauth::OAuth::VERSION = T.let(T.unsafe(nil), String)
