# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `ruumba` gem.
# Please instead update this file by running `bin/tapioca gem ruumba`.


# @author Andrew Clemons <andrew.clemons@gmail.com>
#
# source://ruumba//lib/ruumba/iterators.rb#4
module Ruumba; end

# Generates analyzer objects that, when run, delegate
# to RuboCop for linting (style, correctness, &c).
#
# source://ruumba//lib/ruumba/analyzer.rb#19
class Ruumba::Analyzer
  # @return [Analyzer] a new instance of Analyzer
  #
  # source://ruumba//lib/ruumba/analyzer.rb#20
  def initialize(opts = T.unsafe(nil)); end

  # Performs static analysis on the provided directory.
  #
  # @param dir [Array<String>] The directories / files to analyze.
  #
  # source://ruumba//lib/ruumba/analyzer.rb#26
  def run(files_or_dirs = T.unsafe(nil)); end

  private

  # source://ruumba//lib/ruumba/analyzer.rb#40
  def analyze(temp_dir, files_or_dirs); end

  # source://ruumba//lib/ruumba/analyzer.rb#88
  def arguments; end

  # @return [Boolean]
  #
  # source://ruumba//lib/ruumba/analyzer.rb#76
  def auto_correct?; end

  # source://ruumba//lib/ruumba/analyzer.rb#104
  def auto_correct_marker; end

  # source://ruumba//lib/ruumba/analyzer.rb#122
  def copy_erb_file(file, contents, temp_dir); end

  # source://ruumba//lib/ruumba/analyzer.rb#114
  def digestor; end

  # @return [Boolean]
  #
  # source://ruumba//lib/ruumba/analyzer.rb#96
  def disable_rb_extension?; end

  # source://ruumba//lib/ruumba/analyzer.rb#72
  def extension; end

  # source://ruumba//lib/ruumba/analyzer.rb#118
  def file_mappings; end

  # Returns the value of attribute options.
  #
  # source://ruumba//lib/ruumba/analyzer.rb#38
  def options; end

  # source://ruumba//lib/ruumba/analyzer.rb#110
  def parser; end

  # source://ruumba//lib/ruumba/analyzer.rb#100
  def pwd; end

  # @return [Boolean]
  #
  # source://ruumba//lib/ruumba/analyzer.rb#80
  def stdin?; end

  # source://ruumba//lib/ruumba/analyzer.rb#84
  def stdin_filename; end

  # source://ruumba//lib/ruumba/analyzer.rb#152
  def temp_filename_for(file, temp_dir); end
end

# Responsible for extracted auto corrected code and updating the original ERBs files
#
# source://ruumba//lib/ruumba/correctors.rb#5
module Ruumba::Correctors; end

# Corrector for when normal file checking
#
# source://ruumba//lib/ruumba/correctors.rb#55
class Ruumba::Correctors::FileCorrector
  include ::Ruumba::Correctors::Replacer

  # @return [FileCorrector] a new instance of FileCorrector
  #
  # source://ruumba//lib/ruumba/correctors.rb#58
  def initialize(digestor, parser); end

  # source://ruumba//lib/ruumba/correctors.rb#63
  def correct(_stdout, _stderr, file_mappings); end

  private

  # Returns the value of attribute digestor.
  #
  # source://ruumba//lib/ruumba/correctors.rb#77
  def digestor; end

  # Returns the value of attribute parser.
  #
  # source://ruumba//lib/ruumba/correctors.rb#77
  def parser; end
end

# Module to help replace code
#
# source://ruumba//lib/ruumba/correctors.rb#7
module Ruumba::Correctors::Replacer
  # @yield [replaced_output]
  #
  # source://ruumba//lib/ruumba/correctors.rb#8
  def handle_corrected_output(old_digest, new_contents, original_contents); end
end

# Corrector for when the checked file was passed through stdin.
#
# source://ruumba//lib/ruumba/correctors.rb#22
class Ruumba::Correctors::StdinCorrector
  include ::Ruumba::Correctors::Replacer

  # @return [StdinCorrector] a new instance of StdinCorrector
  #
  # source://ruumba//lib/ruumba/correctors.rb#25
  def initialize(digestor, parser); end

  # source://ruumba//lib/ruumba/correctors.rb#30
  def correct(stdout, stderr, file_mappings); end

  private

  # Returns the value of attribute digestor.
  #
  # source://ruumba//lib/ruumba/correctors.rb#51
  def digestor; end

  # Returns the value of attribute parser.
  #
  # source://ruumba//lib/ruumba/correctors.rb#51
  def parser; end
end

# Generates analyzer objects that, when run, delegate
# to RuboCop for linting (style, correctness, &c).
#
# source://ruumba//lib/ruumba/iterators.rb#7
module Ruumba::Iterators; end

# Iterator which returns matching files from the given directory or file list
#
# source://ruumba//lib/ruumba/iterators.rb#26
class Ruumba::Iterators::DirectoryIterator
  include ::Enumerable

  # @return [DirectoryIterator] a new instance of DirectoryIterator
  #
  # source://ruumba//lib/ruumba/iterators.rb#29
  def initialize(files_or_dirs, temp_dir); end

  # source://ruumba//lib/ruumba/iterators.rb#34
  def each(&block); end

  private

  # source://ruumba//lib/ruumba/iterators.rb#66
  def expand_path(file_or_dir); end

  # source://ruumba//lib/ruumba/iterators.rb#44
  def files; end

  # Returns the value of attribute files_or_dirs.
  #
  # source://ruumba//lib/ruumba/iterators.rb#42
  def files_or_dirs; end

  # source://ruumba//lib/ruumba/iterators.rb#56
  def full_list; end

  # Returns the value of attribute temp_dir.
  #
  # source://ruumba//lib/ruumba/iterators.rb#42
  def temp_dir; end
end

# Iterator which returns the file passed in via stdin
#
# source://ruumba//lib/ruumba/iterators.rb#9
class Ruumba::Iterators::StdinIterator
  include ::Enumerable

  # @return [StdinIterator] a new instance of StdinIterator
  #
  # source://ruumba//lib/ruumba/iterators.rb#12
  def initialize(file); end

  # source://ruumba//lib/ruumba/iterators.rb#16
  def each(&block); end

  private

  # Returns the value of attribute file.
  #
  # source://ruumba//lib/ruumba/iterators.rb#22
  def file; end
end

# Responsible for extracting interpolated Ruby.
#
# source://ruumba//lib/ruumba/parser.rb#7
class Ruumba::Parser
  # @return [Parser] a new instance of Parser
  #
  # source://ruumba//lib/ruumba/parser.rb#11
  def initialize(region_start_marker = T.unsafe(nil)); end

  # Extracts Ruby code from an ERB template.
  #
  # @return [String] The extracted ruby code
  #
  # source://ruumba//lib/ruumba/parser.rb#17
  def extract(contents); end

  # source://ruumba//lib/ruumba/parser.rb#41
  def replace(old_contents, new_contents); end

  private

  # source://ruumba//lib/ruumba/parser.rb#110
  def extract_match(file_text, start_index, end_index, match_marker); end

  # source://ruumba//lib/ruumba/parser.rb#90
  def handle_region_before(match_start, prev_end_index, file_text, extracted_ruby); end

  # @return [Boolean]
  #
  # source://ruumba//lib/ruumba/parser.rb#106
  def needs_stmt_delimiter?(last_match, region_before); end

  # source://ruumba//lib/ruumba/parser.rb#79
  def parse(contents); end

  # Returns the value of attribute region_start_marker.
  #
  # source://ruumba//lib/ruumba/parser.rb#77
  def region_start_marker; end
end

# The regular expression to capture interpolated Ruby.
#
# source://ruumba//lib/ruumba/parser.rb#9
Ruumba::Parser::ERB_REGEX = T.let(T.unsafe(nil), Regexp)

# Runs rubocop on the files in the given target_directory
#
# source://ruumba//lib/ruumba/rubocop_runner.rb#7
class Ruumba::RubocopRunner
  # @return [RubocopRunner] a new instance of RubocopRunner
  #
  # source://ruumba//lib/ruumba/rubocop_runner.rb#8
  def initialize(arguments, current_directory, target_directory, stdin, rb_extension_enabled); end

  # Executes rubocop, updating filenames in the output if needed.
  #
  # @return the exit code of the rubocop process
  #
  # source://ruumba//lib/ruumba/rubocop_runner.rb#23
  def execute; end

  private

  # Returns the value of attribute arguments.
  #
  # source://ruumba//lib/ruumba/rubocop_runner.rb#43
  def arguments; end

  # Returns the value of attribute current_directory.
  #
  # source://ruumba//lib/ruumba/rubocop_runner.rb#43
  def current_directory; end

  # source://ruumba//lib/ruumba/rubocop_runner.rb#45
  def munge_output(output); end

  # Returns the value of attribute rb_extension_enabled.
  #
  # source://ruumba//lib/ruumba/rubocop_runner.rb#43
  def rb_extension_enabled; end

  # Returns the value of attribute replacements.
  #
  # source://ruumba//lib/ruumba/rubocop_runner.rb#43
  def replacements; end

  # Returns the value of attribute stdin.
  #
  # source://ruumba//lib/ruumba/rubocop_runner.rb#43
  def stdin; end

  # Returns the value of attribute target_directory.
  #
  # source://ruumba//lib/ruumba/rubocop_runner.rb#43
  def target_directory; end
end
