# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `sprockets-es6` gem.
# Please instead update this file by running `bin/tapioca gem sprockets-es6`.


# source://sprockets-es6//lib/sprockets/es6/version.rb#1
module Sprockets
  extend ::Sprockets::Utils
  extend ::Sprockets::URIUtils
  extend ::Sprockets::PathUtils
  extend ::Sprockets::DigestUtils
  extend ::Sprockets::PathDigestUtils
  extend ::Sprockets::Dependencies
  extend ::Sprockets::Compressing
  extend ::Sprockets::Exporting
  extend ::Sprockets::Processing
  extend ::Sprockets::HTTPUtils
  extend ::Sprockets::Transformers
  extend ::Sprockets::Mime
  extend ::Sprockets::Paths
end

# source://sprockets-es6//lib/sprockets/es6/version.rb#2
class Sprockets::ES6
  # @return [ES6] a new instance of ES6
  #
  # source://sprockets-es6//lib/sprockets/es6.rb#49
  def initialize(options = T.unsafe(nil)); end

  # Returns the value of attribute cache_key.
  #
  # source://sprockets-es6//lib/sprockets/es6.rb#43
  def cache_key; end

  # source://sprockets-es6//lib/sprockets/es6.rb#61
  def call(input); end

  # source://sprockets-es6//lib/sprockets/es6.rb#45
  def configuration_hash; end

  # source://sprockets-es6//lib/sprockets/es6.rb#69
  def transform(data, opts); end

  # source://sprockets-es6//lib/sprockets/es6.rb#73
  def transformation_options(input); end

  class << self
    # source://sprockets-es6//lib/sprockets/es6.rb#37
    def cache_key; end

    # source://sprockets-es6//lib/sprockets/es6.rb#33
    def call(input); end

    # Returns the value of attribute configuration.
    #
    # source://sprockets-es6//lib/sprockets/es6.rb#11
    def configuration; end

    # Sets the attribute configuration
    #
    # @param value the value to set the attribute configuration to.
    #
    # source://sprockets-es6//lib/sprockets/es6.rb#11
    def configuration=(_arg0); end

    # source://sprockets-es6//lib/sprockets/es6.rb#13
    def configuration_hash; end

    # @yield [configuration]
    #
    # source://sprockets-es6//lib/sprockets/es6.rb#24
    def configure; end

    # source://sprockets-es6//lib/sprockets/es6.rb#20
    def instance; end

    # source://sprockets-es6//lib/sprockets/es6.rb#29
    def reset_configuration; end
  end
end

# source://sprockets-es6//lib/sprockets/es6/version.rb#3
Sprockets::ES6::VERSION = T.let(T.unsafe(nil), String)
