# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `worker_killer` gem.
# Please instead update this file by running `bin/tapioca gem worker_killer`.


# source://worker_killer//lib/worker_killer/version.rb#3
module WorkerKiller
  class << self
    # Returns the value of attribute configuration.
    #
    # source://worker_killer//lib/worker_killer.rb#12
    def configuration; end

    # Sets the attribute configuration
    #
    # @param value the value to set the attribute configuration to.
    #
    # source://worker_killer//lib/worker_killer.rb#12
    def configuration=(_arg0); end

    # @yield [configuration]
    #
    # source://worker_killer//lib/worker_killer.rb#16
    def configure; end

    # source://worker_killer//lib/worker_killer.rb#23
    def randomize(integer); end
  end
end

# Methods for configuring WorkerKiller
#
# source://worker_killer//lib/worker_killer/configuration.rb#5
class WorkerKiller::Configuration
  # Override defaults for configuration
  # Attempts configuration is deprecated and unsed
  #
  # @return [Configuration] a new instance of Configuration
  #
  # source://worker_killer//lib/worker_killer/configuration.rb#12
  def initialize(quit_attempts: T.unsafe(nil), term_attempts: T.unsafe(nil)); end

  # Attempts configuration is deprecated and unsed
  #
  # source://worker_killer//lib/worker_killer/configuration.rb#8
  def logger; end

  # Attempts configuration is deprecated and unsed
  #
  # source://worker_killer//lib/worker_killer/configuration.rb#8
  def logger=(_arg0); end

  # Attempts configuration is deprecated and unsed
  #
  # source://worker_killer//lib/worker_killer/configuration.rb#8
  def quit_attempts; end

  # Attempts configuration is deprecated and unsed
  #
  # source://worker_killer//lib/worker_killer/configuration.rb#8
  def quit_attempts=(_arg0); end

  # Attempts configuration is deprecated and unsed
  #
  # source://worker_killer//lib/worker_killer/configuration.rb#8
  def term_attempts; end

  # Attempts configuration is deprecated and unsed
  #
  # source://worker_killer//lib/worker_killer/configuration.rb#8
  def term_attempts=(_arg0); end
end

# source://worker_killer//lib/worker_killer/count_limiter.rb#2
class WorkerKiller::CountLimiter
  # @return [CountLimiter] a new instance of CountLimiter
  #
  # source://worker_killer//lib/worker_killer/count_limiter.rb#6
  def initialize(min: T.unsafe(nil), max: T.unsafe(nil), verbose: T.unsafe(nil)); end

  # source://worker_killer//lib/worker_killer/count_limiter.rb#22
  def check; end

  # source://worker_killer//lib/worker_killer/count_limiter.rb#17
  def initialize_limits; end

  # Returns the value of attribute left.
  #
  # source://worker_killer//lib/worker_killer/count_limiter.rb#4
  def left; end

  # Returns the value of attribute limit.
  #
  # source://worker_killer//lib/worker_killer/count_limiter.rb#4
  def limit; end

  # source://worker_killer//lib/worker_killer/count_limiter.rb#40
  def logger; end

  # Returns the value of attribute max.
  #
  # source://worker_killer//lib/worker_killer/count_limiter.rb#4
  def max; end

  # Returns the value of attribute min.
  #
  # source://worker_killer//lib/worker_killer/count_limiter.rb#4
  def min; end

  # Returns the value of attribute started_at.
  #
  # source://worker_killer//lib/worker_killer/count_limiter.rb#4
  def started_at; end
end

# source://worker_killer//lib/worker_killer/killer.rb#2
module WorkerKiller::Killer; end

# source://worker_killer//lib/worker_killer/killer.rb#3
class WorkerKiller::Killer::Base
  # @return [Base] a new instance of Base
  #
  # source://worker_killer//lib/worker_killer/killer.rb#7
  def initialize(logger: T.unsafe(nil), **_kwargs); end

  # Returns the value of attribute config.
  #
  # source://worker_killer//lib/worker_killer/killer.rb#5
  def config; end

  # Sets the attribute config
  #
  # @param value the value to set the attribute config to.
  #
  # source://worker_killer//lib/worker_killer/killer.rb#5
  def config=(_arg0); end

  # :nocov:
  #
  # source://worker_killer//lib/worker_killer/killer.rb#32
  def do_kill(*_args); end

  # source://worker_killer//lib/worker_killer/killer.rb#14
  def kill(start_time, **params); end

  # Returns the value of attribute kill_attempts.
  #
  # source://worker_killer//lib/worker_killer/killer.rb#5
  def kill_attempts; end

  # Sets the attribute kill_attempts
  #
  # @param value the value to set the attribute kill_attempts to.
  #
  # source://worker_killer//lib/worker_killer/killer.rb#5
  def kill_attempts=(_arg0); end

  # :nocov:
  #
  # source://worker_killer//lib/worker_killer/killer.rb#37
  def logger; end
end

# source://worker_killer//lib/worker_killer/killer/delayed_job.rb#3
class WorkerKiller::Killer::DelayedJob < ::WorkerKiller::Killer::Base
  # source://worker_killer//lib/worker_killer/killer/delayed_job.rb#5
  def do_kill(sig, pid, alive_sec, dj:, **_kwargs); end
end

# source://worker_killer//lib/worker_killer/killer/passenger.rb#3
class WorkerKiller::Killer::Passenger < ::WorkerKiller::Killer::Base
  # @return [Passenger] a new instance of Passenger
  #
  # source://worker_killer//lib/worker_killer/killer/passenger.rb#7
  def initialize(path: T.unsafe(nil), **kwrags); end

  # source://worker_killer//lib/worker_killer/killer/passenger.rb#16
  def do_kill(sig, pid, alive_sec, **params); end

  # Returns the value of attribute passenger_config.
  #
  # source://worker_killer//lib/worker_killer/killer/passenger.rb#5
  def passenger_config; end

  class << self
    # source://worker_killer//lib/worker_killer/killer/passenger.rb#36
    def check_passenger_config(path); end

    # source://worker_killer//lib/worker_killer/killer/passenger.rb#44
    def check_passenger_config!(path); end
  end
end

# source://worker_killer//lib/worker_killer/killer/puma.rb#3
class WorkerKiller::Killer::Puma < ::WorkerKiller::Killer::Base
  # @return [Puma] a new instance of Puma
  #
  # source://worker_killer//lib/worker_killer/killer/puma.rb#7
  def initialize(puma_plugin:, worker_num: T.unsafe(nil), **kwargs); end

  # source://worker_killer//lib/worker_killer/killer/puma.rb#13
  def do_kill(sig, pid, alive_sec, **_params); end

  # Returns the value of attribute worker_num.
  #
  # source://worker_killer//lib/worker_killer/killer/puma.rb#5
  def worker_num; end

  # Sets the attribute worker_num
  #
  # @param value the value to set the attribute worker_num to.
  #
  # source://worker_killer//lib/worker_killer/killer/puma.rb#5
  def worker_num=(_arg0); end
end

# source://worker_killer//lib/worker_killer/killer/signal.rb#3
class WorkerKiller::Killer::Signal < ::WorkerKiller::Killer::Base
  # source://worker_killer//lib/worker_killer/killer/signal.rb#5
  def do_kill(sig, pid, alive_sec, **_kwargs); end
end

# source://worker_killer//lib/worker_killer/memory_limiter.rb#4
class WorkerKiller::MemoryLimiter
  # @return [MemoryLimiter] a new instance of MemoryLimiter
  #
  # source://worker_killer//lib/worker_killer/memory_limiter.rb#8
  def initialize(min:, max:, check_cycle: T.unsafe(nil), verbose: T.unsafe(nil)); end

  # source://worker_killer//lib/worker_killer/memory_limiter.rb#34
  def check; end

  # Returns the value of attribute check_cycle.
  #
  # source://worker_killer//lib/worker_killer/memory_limiter.rb#6
  def check_cycle; end

  # source://worker_killer//lib/worker_killer/memory_limiter.rb#48
  def do_check(rss); end

  # source://worker_killer//lib/worker_killer/memory_limiter.rb#26
  def initialize_limits(rss); end

  # Returns the value of attribute limit.
  #
  # source://worker_killer//lib/worker_killer/memory_limiter.rb#6
  def limit; end

  # source://worker_killer//lib/worker_killer/memory_limiter.rb#71
  def logger; end

  # Returns the value of attribute max.
  #
  # source://worker_killer//lib/worker_killer/memory_limiter.rb#6
  def max; end

  # Returns the value of attribute min.
  #
  # source://worker_killer//lib/worker_killer/memory_limiter.rb#6
  def min; end

  # source://worker_killer//lib/worker_killer/memory_limiter.rb#64
  def set_limits(min, max); end

  # Returns the value of attribute started_at.
  #
  # source://worker_killer//lib/worker_killer/memory_limiter.rb#6
  def started_at; end
end

# source://worker_killer//lib/worker_killer/middleware.rb#5
class WorkerKiller::Middleware
  # inhibitions - список адресов, которые будут времнно блокировать перезапуск воркеров:
  # Rails.application.config.middleware.insert_before(
  #   Rack::Sendfile,
  #   WorkerKiller::Middleware::RequestsLimiter, killer:, min: 2, max: 3, inhibitions: ['/test']
  # )
  #
  # @return [Middleware] a new instance of Middleware
  #
  # source://worker_killer//lib/worker_killer/middleware.rb#15
  def initialize(app, killer:, klass:, interval: T.unsafe(nil), inhibitions: T.unsafe(nil), reaction: T.unsafe(nil), **opts); end

  # source://worker_killer//lib/worker_killer/middleware.rb#30
  def call(env); end

  # source://worker_killer//lib/worker_killer/middleware.rb#44
  def call_with_inhibition(env, path_info, &after); end

  # source://worker_killer//lib/worker_killer/middleware.rb#92
  def default_kill(l, k); end

  # Returns the value of attribute inhibitions.
  #
  # source://worker_killer//lib/worker_killer/middleware.rb#7
  def inhibitions; end

  # source://worker_killer//lib/worker_killer/middleware.rb#96
  def inihibit(_path_info); end

  # Returns the value of attribute interval.
  #
  # source://worker_killer//lib/worker_killer/middleware.rb#7
  def interval; end

  # Returns the value of attribute killer.
  #
  # source://worker_killer//lib/worker_killer/middleware.rb#7
  def killer; end

  # Returns the value of attribute limiter.
  #
  # source://worker_killer//lib/worker_killer/middleware.rb#7
  def limiter; end

  # source://worker_killer//lib/worker_killer/middleware.rb#109
  def logger; end

  # source://worker_killer//lib/worker_killer/middleware.rb#80
  def react; end

  # Returns the value of attribute reaction.
  #
  # source://worker_killer//lib/worker_killer/middleware.rb#7
  def reaction; end

  # source://worker_killer//lib/worker_killer/middleware.rb#100
  def release; end

  # source://worker_killer//lib/worker_killer/middleware.rb#68
  def wrap_rack_response_body(rack_response_body, &after); end
end

# source://worker_killer//lib/worker_killer/middleware.rb#121
class WorkerKiller::Middleware::OOMLimiter < ::WorkerKiller::Middleware
  # @return [OOMLimiter] a new instance of OOMLimiter
  #
  # source://worker_killer//lib/worker_killer/middleware.rb#123
  def initialize(app, **opts); end
end

# source://worker_killer//lib/worker_killer/middleware.rb#113
class WorkerKiller::Middleware::RequestsLimiter < ::WorkerKiller::Middleware
  # @return [RequestsLimiter] a new instance of RequestsLimiter
  #
  # source://worker_killer//lib/worker_killer/middleware.rb#115
  def initialize(app, **opts); end
end

# source://worker_killer//lib/worker_killer/version.rb#5
WorkerKiller::VERSION = T.let(T.unsafe(nil), String)
