// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ApplicationController from "./application_controller"
application.register("application", ApplicationController)

import CommentBulkController from "./comment_bulk_controller"
application.register("comment-bulk", CommentBulkController)

import CommentController from "./comment_controller"
application.register("comment", CommentController)

import CommentFormController from "./comment_form_controller"
application.register("comment-form", CommentFormController)

import ConsentController from "./consent_controller"
application.register("consent", ConsentController)

import CtaParticlesController from "./cta_particles_controller"
application.register("cta-particles", CtaParticlesController)

import DismissibleController from "./dismissible_controller"
application.register("dismissible", DismissibleController)

import ElectronUgcLauncherController from "./electron_ugc_launcher_controller"
application.register("electron-ugc-launcher", ElectronUgcLauncherController)

import EnhancedApplicationController from "./enhanced_application_controller"
application.register("enhanced-application", EnhancedApplicationController)

import ExperienceStateController from "./experience_state_controller"
application.register("experience-state", ExperienceStateController)

import ExperienceUploadController from "./experience_upload_controller"
application.register("experience-upload", ExperienceUploadController)

import FormAutoSubmitController from "./form_auto_submit_controller"
application.register("form-auto-submit", FormAutoSubmitController)

import FoundationController from "./foundation_controller"
application.register("foundation", FoundationController)

import HyperspaceController from "./hyperspace_controller"
application.register("hyperspace", HyperspaceController)

import InstanceSettingsController from "./instance_settings_controller"
application.register("instance-settings", InstanceSettingsController)

import LanguagePickerController from "./language_picker_controller"
application.register("language-picker", LanguagePickerController)

import LenisController from "./lenis_controller"
application.register("lenis", LenisController)

import LinkController from "./link_controller"
application.register("link", LinkController)

import LlmController from "./llm_controller"
application.register("llm", LlmController)

import MetaverseMapController from "./metaverse_map_controller"
application.register("metaverse-map", MetaverseMapController)

import MetaversePanelSwitchController from "./metaverse_panel_switch_controller"
application.register("metaverse-panel-switch", MetaversePanelSwitchController)

import NavigationShortcutsController from "./navigation_shortcuts_controller"
application.register("navigation-shortcuts", NavigationShortcutsController)

import OffCanvasController from "./off_canvas_controller"
application.register("off-canvas", OffCanvasController)

import OnekoController from "./oneko_controller"
application.register("oneko", OnekoController)

import OnekoSkinPickerController from "./oneko_skin_picker_controller"
application.register("oneko-skin-picker", OnekoSkinPickerController)

import ParallaxBackgroundController from "./parallax_background_controller"
application.register("parallax-background", ParallaxBackgroundController)

import RaindropController from "./raindrop_controller"
application.register("raindrop", RaindropController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import SearchUrlUpdaterController from "./search_url_updater_controller"
application.register("search-url-updater", SearchUrlUpdaterController)

import SidebarPopoverController from "./sidebar_popover_controller"
application.register("sidebar-popover", SidebarPopoverController)

import SyncModeController from "./sync_mode_controller"
application.register("sync-mode", SyncModeController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)
