name: "Code Quality Analysis"
description: "Run code quality analysis tools"

inputs:
    tool:
        description: "Code quality tool to run (fasterer, coffeelint, typos)"
        required: true

runs:
    using: "composite"
    steps:
        - name: Run Fasterer
          if: inputs.tool == 'fasterer'
          shell: bash
          run: RUBYOPT='--yjit --yjit-exec-mem-size=2 --yjit-mem-size=3 --yjit-call-threshold=1 --yjit-cold-threshold=1000000 --yjit-code-gc' bundle exec fasterer

        - name: Run Coffeelint
          if: inputs.tool == 'coffeelint'
          shell: bash
          run: |
              echo "Searching for CoffeeScript files..."
              coffee_files=$(find . -path ./node_modules -prune -o -path ./vendor -prune -o -path ./tmp -prune -o -name '*.coffee' -print)
              if [ -n "$coffee_files" ]; then
                echo "Found CoffeeScript files:"
                echo "$coffee_files"
                echo "Running coffeelint..."
                echo "$coffee_files" | xargs bun coffeelint -f coffeelint.json
              else
                echo "No .coffee files found, skipping Coffeelint"
              fi

        - name: typos-action
          if: inputs.tool == 'typos'
          uses: crate-ci/typos@v1.33.1
