# Brakeman configuration
---
:ignore:
    - :fingerprint: !binary |-
          # This is a false positive - we validate the federated_uri parameter
          # through validate_and_sanitize_federated_uri before redirecting
          ZmVkZXJhdGVkX3VyaQ==
      :note: |
          The federated_uri parameter is validated through validate_and_sanitize_federated_uri
          which ensures only HTTPS URLs to trusted domains are allowed. This is not an
          open redirect vulnerability.
      :check: Redirect
      :file: app/controllers/experiences_controller.rb
