require:
    - ./lib/haml_lint/linter/hardcoded_string_linter.rb

exclude:
    - "vendor/**/*"
    - "vendor/**/*.haml"
    - "vendor/**/*.html.haml"
    - "**/vendor/**/*"
    - "**/vendor/**/*.haml"
    - "**/vendor/**/*.html.haml"
    - ".codeql/**/*"

linters:
    LineLength:
        enabled: false
    RuboCop:
        enabled: false
    SpaceInsideHashAttributes:
        enabled: false
    HardcodedStringLinter:
        enabled: false
        excluded_attributes: ["class", "id", "data-test"]
        autocorrect: true
        i18n_load_path: "config/locales/en.yml"
    InlineStyles:
        enabled: false
    ViewLength:
        enabled: false
