version: "3.8"

services:
  web:
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-${UID:-1000}}
    volumes:
      - ./log:/rails/log
      - ./storage:/rails/storage
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis-db:6379
      - DATABASE_URL=mysql2://root:password@mysql-db/
    secrets:
      - source: master_key
        target: /rails/config/master.key
    depends_on:
      redis-db:
        condition: service_started
      mysql-db:
        condition: service_healthy

  mysql-db:
    image: mysql:8.0
    command:
      - --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./tmp/mysql-db:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=password
      interval: 2s
      timeout: 5s
      retries: 30

  redis-db:
    image: redis

secrets:
  master_key:
    file: ./config/master.key
