# frozen_string_literal: true
# shareable_constant_value: literal

# Make the gem thing SHUT UP
begin
  Gem::Specification.instance_variable_set(:@all, nil)
rescue StandardError
  nil
end

source "https://rubygems.org"

ruby ">= 3.3.7"

gem "active_hashcash"
gem "active_storage_db"
gem "active_storage_validations"
gem "argon2"
gem "audits1984"
gem "better_html"
gem "bootsnap", require: false
gem "cancancan"
gem "capybara"
gem "chunky_png"
gem "codemirror-rails"
gem "comfortable_media_surfer"
gem "console1984"
gem "counter_culture"
gem "federails"
gem "federails-moderation"
gem "fiddle"
gem "friendly_id"
gem "gemoji"
gem "google_robotstxt_parser", path: "vendor/gems/google_robotstxt_parser"
gem "graphql_rails"
gem "hiredis-client", path: "vendor/gems/hiredis-client"
gem "htmlcompressor", "~> 0.4.0"
gem "httparty"
gem "image_processing"
gem "inky-rb", require: "inky"
gem "invisible_captcha"
gem "jbuilder"
gem "json"
gem "kaminari-i18n"
gem "kredis"
gem "lockbox"
gem "nokogiri"
gem "oj"
gem "omniauth_openid_connect"
gem "ostruct"
gem "passenger", ">= 6.0.20", require: "phusion_passenger/rack_handler"
gem "permessage_deflate"
gem "premailer-rails"
gem "propshaft"
gem "rack-attack", ">= 6.8.0"
gem "rack-brotli"
gem "rack-cors"
gem "rack-mini-profiler"
gem "rails"
gem "rails-controller-testing"
gem "rails_http_preload"
gem "rails-i18n"
gem "re2"
gem "reactionview", ">= 0.1.3"
gem "react_on_rails", "16.0.0"
gem "redis"
gem "reform"
gem "rodauth-guest"
gem "rodauth-i18n"
gem "rodauth-model"
gem "rodauth-oauth"
gem "rodauth-omniauth"
gem "rodauth-pwned"
gem "rodauth-rails"
gem "rolify"
gem "rspec"
gem "rubyzip"
gem "selenium-webdriver"
gem "sentry-rails"
gem "sentry-ruby"
gem "sequel-activerecord_connection"
gem "shakapacker", "8.4.0"
gem "sidekiq"
gem "sidekiq-cron"
gem "sitemap_generator"
gem "slim"
gem "slim-rails"
gem "stimulus-rails"
gem "stimulus_reflex", "3.5.3"
gem "sys-filesystem"
gem "thor", ">= 1.4.0"
gem "thredded", "~> 1.2"
gem "thredded-markdown_coderay"
gem "thredded-markdown_katex"
gem "tilt"
gem "trailblazer"
gem "trilogy"
gem "turbo_power"
gem "turbo-rails"
gem "tzinfo-data"
gem "unicode"
gem "unidecoder"
gem "view_component"
gem "vite_rails"
gem "voight_kampff"
gem "worker_killer"
gem "zip_kit"

group :development, :test do
  gem "active_record_doctor"
  gem "listen"
end

group :development do
  gem "brakeman"
  gem "erb-formatter"
  gem "erb_lint"
  gem "fasterer"
  gem "i18n-tasks"
  gem "rubocop"
  gem "rubocop-performance"
  gem "rubocop-rails"
  gem "ruumba"
  gem "slim_lint"
  gem "web-console"
end

group :test do
  gem "mocha"
  gem "mysql2"
end
