# frozen_string_literal: true

source "https://rubygems.org"

ruby "3.4.1"

gem "active_hashcash"
gem "active_storage_validations"
gem "argon2"
gem "bootsnap"
gem "cancancan"
gem "federails"
gem "federails-moderation"
gem "fiddle"
gem "foreman"
gem "gitlab-omniauth-openid-connect"
gem "graphql_rails"
gem "grpc"
gem "haml", "~> 5.2"
gem "haml-rails"
gem "httparty"
gem "inky-rb", require: "inky"
gem "invisible_captcha"
gem "jbuilder"
gem "lockbox"
gem "nokogiri"
gem "ostruct"
gem "passenger", ">= 6.0.20"
gem "permessage_deflate"
gem "premailer-rails"
gem "rack-brotli"
gem "rack-cors"
gem "rails"
gem "rails-controller-testing"
gem "re2"
gem "rodauth-guest"
gem "rodauth-i18n"
gem "rodauth-model"
gem "rodauth-oauth"
gem "rodauth-omniauth"
gem "rodauth-pwned"
gem "rodauth-rails"
gem "rolify"
gem "rubyzip"
gem "sentry-rails"
gem "sentry-ruby"
gem "sequel-activerecord_connection"
gem "sitemap_generator"
gem "solid_cable"
gem "solid_cache"
gem "solid_queue"
gem "stimulus-rails"
gem "stimulus_reflex", "3.5.3"
gem "thor", ">= 1.4.0"
gem "tilt"
gem "trilogy"
gem "turbo_power"
gem "turbo-rails"
gem "tzinfo-data", platforms: %i[jruby]
gem "unicode"
gem "unidecoder"
gem "view_component"
gem "vite_rails"
gem "voight_kampff"
gem "zstd-ruby"

group :development, :test do
  gem "debug", platforms: %i[mri]
  gem "dotenv-rails"
end

group :development do
  gem "brakeman"
  gem "bundle-audit"
  gem "dockerfile-rails"
  gem "fasterer"
  gem "grpc-tools"
  gem "haml-lint"
  gem "rubocop"
  gem "rubocop-performance"
  gem "rubocop-rails"
  gem "spring"
  gem "web-console"
end

group :test do
  gem "capybara"
  gem "mocha"
  gem "selenium-webdriver"
end

gem "rack-attack", "~> 6.7"
