# frozen_string_literal: true

source "https://rubygems.org"

ruby "3.4.2"

gem "active_hashcash"
gem "activerecord-enhancedsqlite3-adapter"
gem "active_storage_db"
gem "active_storage_validations"
gem "argon2"
gem "audits1984"
gem "better_html"
gem "bootsnap", require: false
gem "cancancan"
gem "capybara"
gem "chunky_png"
gem "comfortable_media_surfer"
gem "console1984"
gem "federails"
gem "federails-moderation"
gem "fiddle"
gem "freezolite"
gem "friendly_id"
gem "gemoji"
gem "google_robotstxt_parser", path: "vendor/gems/google_robotstxt_parser"
gem "graphql_rails"
gem "haml", "~> 5.2"
gem "haml-rails", "2.1.0"
gem "httparty", ">= 0.24.0"
gem "image_processing"
gem "inky-rb", require: "inky"
gem "invisible_captcha"
gem "jbuilder"
gem "kaminari-i18n"
gem "lockbox"
gem "minify_html", "0.16.4"
gem "nokogiri"
# gem "oj"
gem "counter_culture"
gem "json"
gem "omniauth_openid_connect"
gem "ostruct"
gem "p2p_streams_channel"
gem "passenger", ">= 6.0.20", require: "phusion_passenger/rack_handler"
gem "permessage_deflate"
gem "pg"
gem "premailer-rails"
gem "propshaft"
gem "rack-attack", ">= 6.8.0"
gem "rack-brotli"
gem "rack-cors"
gem "rack-mini-profiler"
gem "rails"
gem "rails-controller-testing"
gem "rails_http_preload"
gem "rails-i18n"
gem "re2"
gem "reactionview", ">= 0.1.3"
gem "react_on_rails", "16.0.0"
gem "reform"
gem "rodauth-guest"
gem "rodauth-i18n"
gem "rodauth-model"
gem "rodauth-oauth"
gem "rodauth-omniauth"
gem "rodauth-pwned"
gem "rodauth-rails"
gem "rolify"
gem "rspec"
gem "rubyzip"
gem "selenium-webdriver"
gem "sentry-rails"
gem "sentry-ruby"
gem "sequel-activerecord_connection"
gem "shakapacker", "8.4.0"
gem "sitemap_generator"
gem "snappy"
gem "solid_cable"
gem "solid_cache", ">= 1.0.8"
gem "solid_queue"
gem "sqlite3"
gem "stimulus-rails"
gem "stimulus_reflex", "3.5.3"
gem "sys-filesystem"
gem "thor", ">= 1.4.0"
gem "thredded", "~> 1.2"
gem "thredded-markdown_coderay"
gem "thredded-markdown_katex"
gem "tilt"
gem "trailblazer"
gem "trilogy"
gem "turbo_power"
gem "turbo-rails"
gem "tzinfo-data"
gem "unicode"
gem "unidecoder"
gem "view_component"
gem "vite_rails"
gem "voight_kampff"
gem "worker_killer"
gem "y-rb_actioncable"
gem "zip_kit"
gem "zstd-ruby"

group :development, :test do
  gem "active_record_doctor"
  gem "listen"
end

group :development do
  gem "brakeman"
  gem "erb-formatter"
  gem "erb_lint"
  gem "fasterer"
  gem "flamegraph"
  gem "haml-lint"
  gem "i18n-tasks"
  gem "overmind"
  gem "redis"
  gem "rubocop"
  gem "rubocop-performance"
  gem "rubocop-rails"
  gem "ruumba"
  gem "web-console"
end

group :test do
  gem "mocha"
  gem "mysql2"
end
