name: "Code Formatting"
description: "Run code formatting tools (Prettier, Rubocop, ESLint, etc.)"

runs:
    using: "composite"
    steps:
        - name: Run Prettier
          shell: bash
          run: bun prettier --write . --ignore-path .prettierignore --log-level warn

        - name: Run Rubocop
          shell: bash
          run: RUBYOPT='--yjit --yjit-exec-mem-size=2 --yjit-mem-size=3 --yjit-call-threshold=1 --yjit-cold-threshold=1000000 ' bin/rubocop -A

        - name: Run haml-lint
          shell: bash
          run: RUBYOPT='--yjit --yjit-exec-mem-size=2 --yjit-mem-size=3 --yjit-call-threshold=1 --yjit-cold-threshold=1000000 ' bundle exec haml-lint --auto-correct app/ config/ lib/ --exclude 'vendor/**/*' --exclude '.codeql/**/*'

        - name: Run ESLint
          shell: bash
          run: bun eslint . --fix

        - name: Run Stylelint
          shell: bash
          run: bun stylelint '**/*.scss' --fix

        - name: Run markdownlint
          shell: bash
          run: bun markdownlint-cli2 '**/*.md' '!**/node_modules/**' '!**/vendor/**' '!**/tmp/**' '!**/log/**' '!**/coverage/**' '!**/storage/**' '!**/licenses/**' --fix --config .markdownlint-cli2.jsonc
