name: "Code Formatting"
description: "Run code formatting tools (Prettier, Rubocop, ESLint, etc.)"

runs:
    using: "composite"
    steps:
        - name: Run Prettier
          shell: bash
          run: pnpm exec prettier --write . --ignore-path .prettierignore --log-level warn

        - name: Run Rubocop
          shell: bash
          run: bin/rubocop -A

        - name: Run haml-lint
          shell: bash
          run: bundle exec haml-lint --auto-correct app/ config/ lib/ --exclude 'vendor/**/*' --exclude '.codeql/**/*'

        - name: Run ESLint
          shell: bash
          run: pnpm exec eslint . --fix

        - name: Run Stylelint
          shell: bash
          run: pnpm exec stylelint '**/*.scss' --fix

        - name: Run markdownlint
          shell: bash
          run: pnpm exec markdownlint-cli2 '**/*.md' '!**/node_modules/**' '!**/vendor/**' '!**/tmp/**' '!**/log/**' '!**/coverage/**' '!**/storage/**' '!**/licenses/**' --fix --config .markdownlint-cli2.jsonc
