name: "Setup Environment"
description: "Set up Ruby, Node.js, pnpm and install dependencies"

runs:
    using: "composite"
    steps:
        - name: Fix File Permissions
          shell: bash
          run: sudo chmod -R u+w .

        - name: Cache Ruby Dependencies
          uses: actions/cache@v3
          with:
              path: vendor/bundle
              key: ${{ runner.os }}-gemfile-${{ hashFiles('**/Gemfile.lock') }}
              restore-keys: |
                  ${{ runner.os }}-gemfile-

        - name: Setup Ruby
          uses: ruby/setup-ruby@v1
          with:
              bundler-cache: false

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
              node-version: "20"
              cache: "pnpm"
              cache-dependency-path: "pnpm-lock.yaml"

        - name: Setup pnpm
          uses: pnpm/action-setup@v4
          with:
              version: 9.15.4
              run_install: false

        - name: Install dependencies
          shell: bash
          run: |
              bundle config set --local path 'vendor/bundle'
              bundle config set without ""
              bundle install --retry 3 --jobs 4
              pnpm install --frozen-lockfile

        - name: Verify bundle installation
          shell: bash
          run: |
              bundle list
              which bundler || echo "Bundler not in PATH"
              bundle exec ruby -v
