# This file contains configuration for recurring jobs to be run by Solid Queue
# Format:
#   job_name:
#     class: JobClass
#     queue: queue_name
#     args: [ arg1, arg2, ... ]
#     schedule: every hour / at 5am every day / etc.

# production:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

development:
  solid_cable_trim:
    class: SolidCable::TrimJob
    queue: default
    schedule: every hour

  cleanup_abandoned_guests:
    class: CleanupAbandonedGuestsJob
    queue: default
    schedule: every day at 3:00am

production:
  solid_cable_trim:
    class: SolidCable::TrimJob
    queue: default
    schedule: every hour

  cleanup_abandoned_guests:
    class: CleanupAbandonedGuestsJob
    queue: default
    schedule: every day at 3:00am
