# This file defines recurring Solid Queue tasks per environment.

shared_tasks: &shared_tasks
    cleanup_abandoned_guests:
        class: CleanupAbandonedGuestsJob
        queue: default
        schedule: every day at 3:00am

    retention_tasks:
        class: PurgeRodauthTokensJob
        queue: maintenance
        schedule: "0 3 * * *"

    integrity_check:
        class: IntegrityCheckJob
        queue: maintenance
        schedule: "0 4 1 1,4,7,10 *" # Quarterly on the 1st of Jan, Apr, Jul, Oct at 4 AM

    metaverse_indexing:
        class: ScheduledIndexingJob
        queue: default
        schedule: "0 */12 * * *" # Every 12 hours (more conservative)

production:
    <<: *shared_tasks

development:
    <<: *shared_tasks

test:
    <<: *shared_tasks
