# This file defines recurring Solid Queue tasks per environment.

shared_tasks: &shared_tasks
    solid_cable_trim:
        class: SolidCable::TrimJob
        queue: default
        schedule: every hour

    cleanup_abandoned_guests:
        class: CleanupAbandonedGuestsJob
        queue: default
        schedule: every day at 3:00am

    retention_tasks:
        class: PurgeRodauthTokensJob
        queue: maintenance
        schedule: "0 3 * * *"

production:
    <<: *shared_tasks

development:
    <<: *shared_tasks

test:
    <<: *shared_tasks
