# typed: strict

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Thredded::BaseMailer`.
# Please instead update this file by running `bin/tapioca dsl Thredded::BaseMailer`.


class Thredded::BaseMailer; end
