module.exports = [
    "enable-quic",
    "block-new-web-contents",
    "disable-background-networking",
    "disable-breakpad",
    "disable-crash-reporter",
    "disable-default-apps",
    "disable-external-intent-requests",
    "disable-file-system",
    ["extension-content-verification", "enforce_strict"],
    ["extensions-install-verification", "enforce_strict"],
    ["num-raster-threads", "0"],
    "process-per-site",
    ["time-zone-for-testing", "UTC"],
    "use-fake-device-for-media-stream",
    ["component-updater", "--disable-pings"],
    [
        "enable-features",
        "BlockInsecurePrivateNetworkRequests,BlockInsecurePrivateNetworkRequestsForNavigations,BrowserDynamicCodeDisabled,CapReferrerToOriginOnCrossOrigin,ClearCrossSiteCrossBrowsingContextGroupWindowName,ContentSettingsPartitioning,DesktopScreenshots,DisableProcessReuse,ElementSuperRareData,EnableCsrssLockdown,EncryptedClientHello,ForceIsolationInfoFrameOriginToTopLevelFrame,GpuAppContainer,ImprovedCookieControls,HstsTopLevelNavigationsOnly,IsolateOrigins,IsolatePrerenders,IsolateSandboxedIframes,LocalNetworkAccessChecks:LocalNetworkAccessChecksWarn/false,LocalNetworkAccessChecksWebRTC,MinimizeAudioProcessingForUnusedOutput,NetworkServiceSandbox,NetworkServiceCodeIntegrity,OpaqueResponseBlockingV01,OriginIsolationHeader,PartitionConnectionsByNetworkIsolationKey,PartitionDomainReliabilityByNetworkIsolationKey,PartitionExpectCTStateByNetworkIsolationKey,PartitionHttpServerPropertiesByNetworkIsolationKey,PartitionNelAndReportingByNetworkIsolationKey,PartitionSSLSessionsByNetworkIsolationKey,PartitionedCookies,PostQuantumCECPQ2,PrefetchPrivacyChanges,ReduceAcceptLanguage,ReduceUserAgent,ReducedReferrerGranularity,RendererAppContainer,RestrictGamepadAccess,SandboxExternalProtocolBlocked,ScopeMemoryCachePerContext,SplitAuthCacheByNetworkIsolationKey,SplitCacheByIncludeCredentials,SplitCacheByNavigationInitiator,SplitCodeCacheByNetworkIsolationKey,SplitCacheByNetworkIsolationKey,SplitHostCacheByNetworkIsolationKey,StrictOriginIsolation,SubframeShutdownDelay,SuppressDifferentOriginSubframeJSDialogs,ThirdPartyStoragePartitioning,WinSboxDisableExtensionPoint,WinSboxDisableKtmComponent,WinSboxRestrictCoreSharingOnRenderer",
    ],
    [
        "disable-features",
        "AcceptCHFrame,AdInterestGroupAPI,AllowClientHintsToThirdParty,AllowSoftwareGLFallbackDueToCrash,AllowSwiftShaderFallback,AllowURNsInIframes,AnonymousIframeOriginTrial,AutofillEnableAccountWalletStorage,AutofillServerCommunication,BrowsingTopics,CssSelectorFragmentAnchor,ClientHintThirdPartyDelegation,ClientHintsDPR,ClientHintsDPR_DEPRECATED,ClientHintsDeviceMemory,ClientHintsDeviceMemory_DEPRECATED,ClientHintsMetaHTTPEquivAcceptCH,ClientHintsMetaNameAcceptCH,ClientHintsResourceWidth,ClientHintsResourceWidth_DEPRECATED,ClientHintsViewportWidth,ClientHintsViewportWidth_DEPRECATED,ComputePressure,ContextMenuPerformanceInfoAndRemoteHintFetching,ConversionMeasurement,CookieDomainRejectNonASCII,CopyLinkToText,CrostiniAdditionalEnterpriseReporting,DocumentReporting,EnableStructuredMetrics,EnterpriseRealtimeExtensionRequest,ExpectCTReporting,EnableTLS13EarlyData,FedCm,Fledge,FontAccess,GreaseUACH,IdleDetection,InterestFeedV2,InterestGroupStorage,Journeys,LensStandalone,MediaDrmPreprovisioning,MediaEngagementBypassAutoplayPolicies,NavigationRequestPreconnect,NetworkTimeServiceQuerying,NotificationTriggers,NTPCardsVisible,NTPPopularSitesBakedInContent,OmniboxTriggerForNoStatePrefetch,OptimizationHints,OptimizationHintsFetching,OptimizationHintsFetchingAnonymousDataConsent,OptimizationHintsFieldTrials,Parakeet,Prerender2,PrefersColorSchemeClientHintHeader,PreloadMediaEngagementData,PrivacySandboxSettings4,Reporting,RetailCoupons,SCTAuditing,SegmentationPlatform,SignedExchangeReportingForDistributors,SignedHTTPExchange,SpeculationRulesPrefetchProxy,SubresourceWebBundles,TabHoverCardImages,TabMetricsLogging,TFLiteLanguageDetectionEnabled,TextFragmentAnchor,SafeBrowsingBetterTelemetryAcrossReports,UsePopularSitesSuggestions,UserAgentClientHint,UserAgentClientHintFullVersionList,UsernameFirstFlow,UsernameFirstFlowFilling,UsernameFirstFlowFallbackCrowdsourcing,ViewportHeightClientHintHeader,WebGPUBlobCache,WebGPUService,WebNFC,WebOTP,WebSQLInThirdPartyContextEnabled,WebXR,WinrtGeolocationImplementation",
    ],
    ["connectivity-check-url", "0.0.0.0"],
    ["crash-server-url", "0.0.0.0"],
    ["gaia-url", "0.0.0.0"],
    ["gcm-checkin-url", "0.0.0.0"],
    ["gcm-mcs-endpoint", "0.0.0.0"],
    ["gcm-registration-url", "0.0.0.0"],
    ["google-apis-url", "0.0.0.0"],
    ["google-base-url", "0.0.0.0"],
    ["google-doodle-url", "0.0.0.0"],
    ["lso-url", "0.0.0.0"],
    ["oauth-account-manager-url", "0.0.0.0"],
    ["override-metrics-upload-url", "0.0.0.0"],
    ["realtime-reporting-url", "0.0.0.0"],
    ["reporting-connector-url", "0.0.0.0"],
    ["sync-url", "0.0.0.0"],
    ["url", "0.0.0.0"],
    ["variations-server-url", "0.0.0.0"],
    ["variations-insecure-server-url", "0.0.0.0"],
    ["cipher-suite-blacklist", "0xc013,0xc014,0x009c,0x009d,0x002f,0x0035"],
    [
        "blink-settings",
        "dnsPrefetchingEnabled=false,preferredColorScheme=1,strictMixedContentChecking=true,strictMixedContentCheckingForPlugin=true,strictlyBlockBlockableMixedContent=true",
    ],
    [
        "disable-blink-features",
        "CrossOriginOpenerPolicyReporting,DirectSockets,HandwritingRecognition,IdleDetection",
    ],
];
