export default [
    "enable-quic",
    "block-new-web-contents",
    "disable-background-networking",
    "disable-breakpad",
    "disable-crash-reporter",
    "disable-default-apps",
    "disable-external-intent-requests",
    "disable-file-system",
    ["extension-content-verification", "enforce_strict"],
    ["extensions-install-verification", "enforce_strict"],
    ["num-raster-threads", "0"],
    ["time-zone-for-testing", "UTC"],
    "use-fake-device-for-media-stream",
    ["component-updater", "--disable-pings"],
    [
        "enable-features",
        "BlockInsecurePrivateNetworkRequests,BlockInsecurePrivateNetworkRequestsForNavigations,BrowserDynamicCodeDisabled,CapReferrerToOriginOnCrossOrigin,ClearCrossSiteCrossBrowsingContextGroupWindowName,ContentSettingsPartitioning,DesktopScreenshots,DisableProcessReuse,ElementSuperRareData,EnableCsrssLockdown,EncryptedClientHello,ForceIsolationInfoFrameOriginToTopLevelFrame,GpuAppContainer,ImprovedCookieControls,HstsTopLevelNavigationsOnly,IsolateOrigins,IsolatePrerenders,IsolateSandboxedIframes,LocalNetworkAccessChecks:LocalNetworkAccessChecksWarn/false,LocalNetworkAccessChecksWebRTC,MinimizeAudioProcessingForUnusedOutput,NetworkServiceSandbox,NetworkServiceCodeIntegrity,OpaqueResponseBlockingV01,OriginIsolationHeader,PartitionConnectionsByNetworkIsolationKey,PartitionDomainReliabilityByNetworkIsolationKey,PartitionExpectCTStateByNetworkIsolationKey,PartitionHttpServerPropertiesByNetworkIsolationKey,PartitionNelAndReportingByNetworkIsolationKey,PartitionSSLSessionsByNetworkIsolationKey,PartitionedCookies,PostQuantumCECPQ2,PrefetchPrivacyChanges,ReduceAcceptLanguage,ReduceUserAgent,ReducedReferrerGranularity,RendererAppContainer,RestrictGamepadAccess,SandboxExternalProtocolBlocked,ScopeMemoryCachePerContext,SplitAuthCacheByNetworkIsolationKey,SplitCacheByIncludeCredentials,SplitCacheByNavigationInitiator,SplitCodeCacheByNetworkIsolationKey,SplitCacheByNetworkIsolationKey,SplitHostCacheByNetworkIsolationKey,StrictOriginIsolation,SubframeShutdownDelay,SuppressDifferentOriginSubframeJSDialogs,ThirdPartyStoragePartitioning,WinSboxDisableExtensionPoint,WinSboxDisableKtmComponent,WinSboxRestrictCoreSharingOnRenderer,HighEfficiencyMode",
    ],
    [
        "disable-features",
        "AcceptCHFrame,AdInterestGroupAPI,AllowClientHintsToThirdParty,AllowSoftwareGLFallbackDueToCrash,AllowSwiftShaderFallback,AllowURNsInIframes,AnonymousIframeOriginTrial,AutofillEnableAccountWalletStorage,AutofillServerCommunication,BrowsingTopics,CssSelectorFragmentAnchor,ClientHintThirdPartyDelegation,ClientHintsDPR,ClientHintsDPR_DEPRECATED,ClientHintsDeviceMemory,ClientHintsDeviceMemory_DEPRECATED,ClientHintsMetaHTTPEquivAcceptCH,ClientHintsMetaNameAcceptCH,ClientHintsResourceWidth,ClientHintsResourceWidth_DEPRECATED,ClientHintsViewportWidth,ClientHintsViewportWidth_DEPRECATED,ComputePressure,ContextMenuPerformanceInfoAndRemoteHintFetching,ConversionMeasurement,CookieDomainRejectNonASCII,CopyLinkToText,CrostiniAdditionalEnterpriseReporting,DocumentReporting,EnableStructuredMetrics,EnterpriseRealtimeExtensionRequest,ExpectCTReporting,EnableTLS13EarlyData,FedCm,Fledge,FontAccess,GreaseUACH,IdleDetection,InterestFeedV2,InterestGroupStorage,Journeys,LensStandalone,MediaDrmPreprovisioning,MediaEngagementBypassAutoplayPolicies,NavigationRequestPreconnect,NetworkTimeServiceQuerying,NotificationTriggers,NTPCardsVisible,NTPPopularSitesBakedInContent,OmniboxTriggerForNoStatePrefetch,OptimizationHints,OptimizationHintsFetching,OptimizationHintsFetchingAnonymousDataConsent,OptimizationHintsFieldTrials,Parakeet,Prerender2,PrefersColorSchemeClientHintHeader,PreloadMediaEngagementData,PrivacySandboxSettings4,Reporting,RetailCoupons,SCTAuditing,SegmentationPlatform,SignedExchangeReportingForDistributors,SignedHTTPExchange,SpeculationRulesPrefetchProxy,SubresourceWebBundles,TabHoverCardImages,TabMetricsLogging,TFLiteLanguageDetectionEnabled,TextFragmentAnchor,SafeBrowsingBetterTelemetryAcrossReports,UsePopularSitesSuggestions,UserAgentClientHint,UserAgentClientHintFullVersionList,UsernameFirstFlow,UsernameFirstFlowFilling,UsernameFirstFlowFallbackCrowdsourcing,ViewportHeightClientHintHeader,WebGPUBlobCache,WebGPUService,WebNFC,WebOTP,WebSQLInThirdPartyContextEnabled,WebXR,WinrtGeolocationImplementation",
    ],
    ["connectivity-check-url", "0.0.0.0"],
    ["crash-server-url", "0.0.0.0"],
    ["gaia-url", "0.0.0.0"],
    ["gcm-checkin-url", "0.0.0.0"],
    ["gcm-mcs-endpoint", "0.0.0.0"],
    ["gcm-registration-url", "0.0.0.0"],
    ["google-apis-url", "0.0.0.0"],
    ["google-base-url", "0.0.0.0"],
    ["google-doodle-url", "0.0.0.0"],
    ["lso-url", "0.0.0.0"],
    ["oauth-account-manager-url", "0.0.0.0"],
    ["override-metrics-upload-url", "0.0.0.0"],
    ["realtime-reporting-url", "0.0.0.0"],
    ["reporting-connector-url", "0.0.0.0"],
    ["sync-url", "0.0.0.0"],
    ["url", "0.0.0.0"],
    ["variations-server-url", "0.0.0.0"],
    ["variations-insecure-server-url", "0.0.0.0"],
    ["cipher-suite-blacklist", "0xc013,0xc014,0x009c,0x009d,0x002f,0x0035"],
    [
        "blink-settings",
        "dnsPrefetchingEnabled=false,preferredColorScheme=1,strictMixedContentChecking=true,strictMixedContentCheckingForPlugin=true,strictlyBlockBlockableMixedContent=true",
    ],
    [
        "disable-blink-features",
        "CrossOriginOpenerPolicyReporting,DirectSockets,HandwritingRecognition,IdleDetection",
    ],
    "isolate-origins",
    ["force-fieldtrials", "disabled"],
    "no-proxy-server",
    "force-high-performance-gpu",
    "disable-ip-privacy-proxy",
    "disable-overscroll-edge-effect",
    "enable-aggressive-domstorage-flushing",
    "enable-adaptive-selection-handle-orientation",
    "disable-domain-reliability",
    "enable-gpu-memory-buffer-compositor-resources",
    "enable-gpu-memory-buffer-video-frames",
    "enable-gpu-rasterization",
    "enable-hardware-overlays",
    "enable-main-frame-before-activation",
    "enable-native-gpu-memory-buffers",
    "enable-natural-scroll-default",
    "enable-potentially-annoying-security-features",
    "enable-sgi-video-sync",
    "enable-skia-graphite",
    "enable-smooth-scrolling",
    "enable-strict-mixed-content-checking",
    "enable-strict-powerful-feature-restrictions",
    "enable-swap-buffers-with-bounds",
    "enable-threaded-texture-mailboxes",
    "enable-touchpad-three-finger-click",
    "enable-webgl-image-chromium",
    "enable-zero-copy",
    "font-cache-shared-handle",
    ["gpu-disk-cache-size-kb", "16384"],
    "gpu-no-context-lost",
    "hide-scrollbars",
    "ignore-gpu-blocklist",
    "isolation-by-default",
    ["max-active-webgl-contexts", "16"],
    "no-default-browser-check",
    "no-first-run",
    "no-pings",
    "no-service-autorun",
    "process-per-site",
    "reduce-user-agent-minor-version",
    "reduce-user-agent-platform-oscpu",
    "request-desktop-sites",
    "restore-last-session",
    "safebrowsing-enable-enhanced-protection",
    ["skia-font-cache-limit-mb", "16"],
    ["skia-resource-cache-limit-mb", "64"],
    ["user-agent", "LibreverseDesktopApp/1.0"],
    "video-capture-use-gpu-memory-buffer",
    [
        "js-flags",
        "--optimize-for-size",
        "--gc_interval=100",
        "--always-osr",
        "--always-sparkplug",
        "--always-use-string-forwarding-table",
        "--concurrent-maglev-high-priority-threads",
        "--concurrent-maglev-max-threads=0",
        "--concurrent-sparkplug-high-priority-threads",
        "--concurrent-sparkplug-max-threads=0",
        "--concurrent-turbofan-max-threads=0",
        "--dict-property-const-tracking",
        "--maglev-inline-api-calls",
        "--maglev-licm",
        "--maglev-non-eager-inlining",
        "--maglev-object-tracking",
        "--maglev-truncation",
        "--turbo-compress-frame-translations",
        "--turbo-instruction-scheduling",
        "--turbo-optimize-inlined-js-wasm-wrappers",
        "--turbo-string-builder",
        "--turbo-verify-allocation",
        "--turbolev",
        "--turbolev-non-eager-inlining",
        "--turboshaft-typed-optimizations",
        "--turboshaft-wasm-in-js-inlining",
        "--abort-on-contradictory-flags",
        "--compact-on-every-full-gc",
        "--concurrent-builtin-generation",
        "--concurrent-marking",
        "--concurrent-marking-high-priority-threads",
        "--cppgc-young-generation",
        "--cppheap-concurrent-marking",
        "--cppheap-incremental-marking",
        "--flush-baseline-code",
        "--flush-code-based-on-time",
        "--gc-experiment-less-compaction",
        "--incremental-marking-always-user-visible",
        "--minor-ms",
        "--experimental-wasm-compilation-hints",
        "--experimental-wasm-simd-opt",
        "--flush-liftoff-code",
        "--wasm-fast-api",
        "--wasm-simd-ssse3-codegen",
    ],
    "force-dark-mode",
    "v8-cache-options=none",
    "aggressive-cache-discard",
    "disk-cache-size=52428800",
    "max-decoded-image-size-mb=128",
];
