#!/bin/sh

# Run static analysis script
git add .
perl scripts/static.pl

# Check if the script failed
if [ $? -ne 0 ]; then
    echo "❌ Static analysis failed. Commit blocked."
    exit 1
fi

# Add any changes made by the static analysis script to the commit
echo "Adding any changes made by static analysis to commit..."
git add -A

echo "Ensuring test database is prepared..."
bin/rails db:schema:load RAILS_ENV=test

echo "✅ Static analysis passed. Proceeding with commit."
